// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "routine-app-server/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// RoutineRepository is an autogenerated mock type for the RoutineRepository type
type RoutineRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: routine
func (_m *RoutineRepository) Create(routine *domain.Routine) error {
	ret := _m.Called(routine)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Routine) error); ok {
		r0 = rf(routine)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRoutineRepository creates a new instance of RoutineRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoutineRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoutineRepository {
	mock := &RoutineRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
