// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "routine-app-server/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// RoutineRepository is an autogenerated mock type for the RoutineRepository type
type RoutineRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: routine
func (_m *RoutineRepository) Create(routine *domain.Routine) error {
	ret := _m.Called(routine)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Routine) error); ok {
		r0 = rf(routine)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with no fields
func (_m *RoutineRepository) FindAll() ([]*domain.Routine, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.Routine
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*domain.Routine, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*domain.Routine); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Routine)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOne provides a mock function with given fields: ID
func (_m *RoutineRepository) FindOne(ID int) (*domain.Routine, error) {
	ret := _m.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *domain.Routine
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Routine, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Routine); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Routine)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRoutineRepository creates a new instance of RoutineRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoutineRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoutineRepository {
	mock := &RoutineRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
