// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "routine-app-server/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// RoutineUseCase is an autogenerated mock type for the RoutineUseCase type
type RoutineUseCase struct {
	mock.Mock
}

// CreateRoutine provides a mock function with given fields: title, interval
func (_m *RoutineUseCase) CreateRoutine(title string, interval string) (*domain.Routine, error) {
	ret := _m.Called(title, interval)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoutine")
	}

	var r0 *domain.Routine
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*domain.Routine, error)); ok {
		return rf(title, interval)
	}
	if rf, ok := ret.Get(0).(func(string, string) *domain.Routine); ok {
		r0 = rf(title, interval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Routine)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(title, interval)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRoutineUseCase creates a new instance of RoutineUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoutineUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoutineUseCase {
	mock := &RoutineUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
