// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// RoutineHandler is an autogenerated mock type for the RoutineHandler type
type RoutineHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *RoutineHandler) Create(c *gin.Context) {
	_m.Called(c)
}

// Delete provides a mock function with given fields: c
func (_m *RoutineHandler) Delete(c *gin.Context) {
	_m.Called(c)
}

// GetAll provides a mock function with given fields: c
func (_m *RoutineHandler) GetAll(c *gin.Context) {
	_m.Called(c)
}

// GetOne provides a mock function with given fields: c
func (_m *RoutineHandler) GetOne(c *gin.Context) {
	_m.Called(c)
}

// Update provides a mock function with given fields: c
func (_m *RoutineHandler) Update(c *gin.Context) {
	_m.Called(c)
}

// NewRoutineHandler creates a new instance of RoutineHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoutineHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoutineHandler {
	mock := &RoutineHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
